deployment:
  tasks:
    - export DEPLOYPATH=/home/a2bremov/swinstead.lol/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --delete --exclude '.git' --exclude '.cpanel.yml' --exclude 'data/links.sqlite' ./ $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/data
    - /usr/bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} +
    - /usr/bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} +
    - /bin/chmod 775 $DEPLOYPATH/data
    - /usr/bin/find $DEPLOYPATH/data -type f -exec /bin/chmod 664 {} +
